# Creación de variables
Se generan variables con el objetivo de proporcionar información adicional.

In [1]:
# Importando la librería de pandas
import pandas as pd  # type: ignore
import os

# Cargar datos desde un archivo CSV
try:
    rutaAbsoluta = os.path.abspath('Accidentes_Aereos_Filtrados.csv')
    df = pd.read_csv(rutaAbsoluta)    
except FileNotFoundError:
    print("El archivo no se encuentra.")

In [3]:
# Mostrar las primeras (5) filas:
print("\u001b[1mVISUALIZACIÓN DE LAS PRIMERAS (5) FILAS\u001b[0m")
df.head() # type: ignore

VISUALIZACIÓN DE LAS PRIMERAS (5) FILAS

,index,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
0,21,12/16/1918,NaN,"Elizabeth, New Jersey",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,97,NaN,1.0,1.0,0.0,NaN
1,22,05/25/1919,NaN,"Cleveland, Ohio",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,61,NaN,1.0,1.0,0.0,Caught fire in midair. The pilot leaped from t...
2,23,07/19/1919,NaN,"Dix Run, Pennsylvania",US Aerial Mail Service,NaN,NaN,De Havilland DH-4,82,NaN,1.0,1.0,0.0,NaN
3,25,10/14/1919,NaN,"Cantonsville, Maryland",US Aerial Mail Service,NaN,NaN,Curtiss R-4LM,32,NaN,1.0,1.0,0.0,NaN
4,27,10/30/1919,NaN,"Long Valley, New Jersey",US Aerial Mail Service,NaN,NaN,De Havilland DH.4,77,NaN,1.0,1.0,0.0,NaN